# Generated by Django 5.0.6 on 2024-07-08 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=100, verbose_name='x-app')),
                ('instagram', models.CharField(max_length=100, verbose_name='instagram')),
                ('linkedin', models.CharField(max_length=100, verbose_name='linkedin')),
                ('you_tube', models.CharField(max_length=100, verbose_name='youtube')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Pofile',
                'verbose_name_plural': 'Social Pofiles',
                'db_table': 'myintro_social_profile',
            },
        ),
    ]
